/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bazff.view;


import bazff.controller.ProductController;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author bisma
 */
public class AddProduct extends javax.swing.JPanel {

    /**
     * Creates new form ProductDataPanel
     */
    private MainWindow mainWindow;
    private ProductController productController;
    public AddProduct(MainWindow window) {
        this.mainWindow = window;
        initComponents();
        productController = new ProductController(window);
    }

    AddProduct() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelHeaderAddProduct = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        PanelAddProduct = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldProductName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldapProductDescription = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxSize = new javax.swing.JComboBox<>();
        jButtonAdd = new javax.swing.JButton();
        jButtonAddProductSize = new javax.swing.JButton();
        jButtonCencel = new javax.swing.JButton();
        LabelImage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1440, 858));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelHeaderAddProduct.setBackground(new java.awt.Color(255, 184, 224));
        PanelHeaderAddProduct.setPreferredSize(new java.awt.Dimension(1440, 127));
        PanelHeaderAddProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        label.setForeground(new java.awt.Color(236, 127, 169));
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("ADD PRODUCT");
        label.setPreferredSize(new java.awt.Dimension(1440, 127));
        PanelHeaderAddProduct.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(PanelHeaderAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelAddProduct.setBackground(new java.awt.Color(255, 230, 248));
        PanelAddProduct.setPreferredSize(new java.awt.Dimension(1440, 730));
        PanelAddProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 127, 169));
        jLabel1.setText("Product Code");
        PanelAddProduct.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 36, -1, -1));

        jTextFieldProductName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldProductName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 1, new java.awt.Color(236, 127, 169)));
        jTextFieldProductName.setInheritsPopupMenu(true);
        PanelAddProduct.add(jTextFieldProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 73, 491, 62));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 127, 169));
        jLabel2.setText("Product Name ");
        PanelAddProduct.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 159, -1, -1));

        jTextFieldapProductDescription.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldapProductDescription.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 1, new java.awt.Color(236, 127, 169)));
        PanelAddProduct.add(jTextFieldapProductDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 196, 491, 62));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 127, 169));
        jLabel4.setText("Price");
        PanelAddProduct.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 276, -1, -1));

        jTextFieldPrice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 1, new java.awt.Color(236, 127, 169)));
        PanelAddProduct.add(jTextFieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 313, 491, 62));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 127, 169));
        jLabel5.setText("Size");
        PanelAddProduct.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 393, -1, -1));

        jComboBoxSize.setBackground(new java.awt.Color(236, 127, 169));
        jComboBoxSize.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jComboBoxSize.setForeground(new java.awt.Color(255, 230, 248));
        jComboBoxSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "XS", "M", "L", "XL", "XXL" }));
        jComboBoxSize.setBorder(null);
        PanelAddProduct.add(jComboBoxSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 430, 180, 62));

        jButtonAdd.setBackground(new java.awt.Color(236, 127, 169));
        jButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 237, 250));
        jButtonAdd.setText("Add");
        jButtonAdd.setBorder(null);
        PanelAddProduct.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 510, 207, 73));

        jButtonAddProductSize.setBackground(new java.awt.Color(236, 127, 169));
        jButtonAddProductSize.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jButtonAddProductSize.setForeground(new java.awt.Color(255, 237, 250));
        jButtonAddProductSize.setText("Add Product Size");
        jButtonAddProductSize.setBorder(null);
        jButtonAddProductSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddProductSizeMouseClicked(evt);
            }
        });
        PanelAddProduct.add(jButtonAddProductSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 611, 491, 73));

        jButtonCencel.setBackground(new java.awt.Color(255, 184, 224));
        jButtonCencel.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jButtonCencel.setForeground(new java.awt.Color(255, 237, 250));
        jButtonCencel.setText("Cancel");
        jButtonCencel.setBorder(null);
        PanelAddProduct.add(jButtonCencel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1102, 510, 207, 73));

        LabelImage.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        LabelImage.setForeground(new java.awt.Color(236, 127, 169));
        LabelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelImage.setText("+");
        LabelImage.setPreferredSize(new java.awt.Dimension(560, 620));
        LabelImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelImageMouseClicked(evt);
            }
        });
        PanelAddProduct.add(LabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 184, 224));
        jPanel2.setPreferredSize(new java.awt.Dimension(415, 580));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelAddProduct.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        add(PanelAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddProductSizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddProductSizeMouseClicked
        productController.addPopUp1();
    }//GEN-LAST:event_jButtonAddProductSizeMouseClicked

    private void LabelImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelImageMouseClicked
        productController.imageChosser(LabelImage, null);
    }//GEN-LAST:event_LabelImageMouseClicked

    public JPanel getPanelAddProduct() {
        return PanelAddProduct;
    }

    public JPanel getPanelHeaderAddProduct() {
        return PanelHeaderAddProduct;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImage;
    private javax.swing.JPanel PanelAddProduct;
    private javax.swing.JPanel PanelHeaderAddProduct;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddProductSize;
    private javax.swing.JButton jButtonCencel;
    private javax.swing.JComboBox<String> jComboBoxSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldProductName;
    private javax.swing.JTextField jTextFieldapProductDescription;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
