/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bazff.view;



import bazff.controller.ProductController;
import bazff.controller.TransactionController;
import javax.swing.JPanel;

/**
 *
 * @author bisma
 */
public class DashBoardPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductDataPanel
     */
    private MainWindow mainWindow;
    private ProductController productController;
    private TransactionController transactionController;

    
    public DashBoardPanel(MainWindow window) {
        this.mainWindow = window;
        initComponents();
        
       
        productController = new ProductController(mainWindow);
        transactionController = new TransactionController(mainWindow);

        int totalMasuk = productController.ambilTotalBarangMasuk();
        jTxtBarangMasuk.setText(String.valueOf(totalMasuk));
        
        int totalTerjual = transactionController.ambilTotalBarangTerjual();
        jTextField1.setText(String.valueOf(totalTerjual));
    }

    DashBoardPanel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderHomePanel = new javax.swing.JPanel();
        PanelHeaderProduct = new javax.swing.JLabel();
        PanelHome = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtBarangMasuk = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1440, 858));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderHomePanel.setBackground(new java.awt.Color(255, 184, 224));
        HeaderHomePanel.setPreferredSize(new java.awt.Dimension(1440, 127));
        HeaderHomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelHeaderProduct.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        PanelHeaderProduct.setForeground(new java.awt.Color(236, 127, 169));
        PanelHeaderProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelHeaderProduct.setText("HOME");
        PanelHeaderProduct.setPreferredSize(new java.awt.Dimension(1440, 127));
        HeaderHomePanel.add(PanelHeaderProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(HeaderHomePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelHome.setBackground(new java.awt.Color(255, 230, 248));
        PanelHome.setPreferredSize(new java.awt.Dimension(1440, 730));
        PanelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 184, 224));
        jPanel5.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Barang Keluar");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 260, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/keranjang2.png"))); // NOI18N
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 184, 224));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("0");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 270, 40));

        PanelHome.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 160, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 184, 224));
        jPanel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Barang Ready");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 260, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/kiriedit.png"))); // NOI18N
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        jTxtBarangMasuk.setEditable(false);
        jTxtBarangMasuk.setBackground(new java.awt.Color(255, 184, 224));
        jTxtBarangMasuk.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jTxtBarangMasuk.setForeground(new java.awt.Color(255, 255, 255));
        jTxtBarangMasuk.setText("0");
        jTxtBarangMasuk.setBorder(null);
        jTxtBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBarangMasukActionPerformed(evt);
            }
        });
        jPanel6.add(jTxtBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 270, 40));

        PanelHome.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        add(PanelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTxtBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBarangMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBarangMasukActionPerformed

    public JPanel getHeaderHomePanel() {
        return HeaderHomePanel;
    }

    public JPanel getPanelHome() {
        return PanelHome;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderHomePanel;
    private javax.swing.JLabel PanelHeaderProduct;
    private javax.swing.JPanel PanelHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTxtBarangMasuk;
    // End of variables declaration//GEN-END:variables
}
