/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bazff.view;


import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author bisma
 */
public class DashBoardPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductDataPanel
     */
    private MainWindow mainWindow;
    
    public DashBoardPanel(MainWindow window) {
        this.mainWindow = window;
        initComponents();
    }

    DashBoardPanel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderHomePanel = new javax.swing.JPanel();
        PanelHeaderProduct = new javax.swing.JLabel();
        PanelHome = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1440, 858));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderHomePanel.setBackground(new java.awt.Color(255, 184, 224));
        HeaderHomePanel.setPreferredSize(new java.awt.Dimension(1440, 127));
        HeaderHomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelHeaderProduct.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        PanelHeaderProduct.setForeground(new java.awt.Color(236, 127, 169));
        PanelHeaderProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelHeaderProduct.setText("HOME");
        PanelHeaderProduct.setPreferredSize(new java.awt.Dimension(1440, 127));
        HeaderHomePanel.add(PanelHeaderProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(HeaderHomePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelHome.setBackground(new java.awt.Color(255, 230, 248));
        PanelHome.setPreferredSize(new java.awt.Dimension(1440, 730));
        PanelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(PanelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getHeaderHomePanel() {
        return HeaderHomePanel;
    }

    public JPanel getPanelHome() {
        return PanelHome;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderHomePanel;
    private javax.swing.JLabel PanelHeaderProduct;
    private javax.swing.JPanel PanelHome;
    // End of variables declaration//GEN-END:variables
}
