/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bazff.view;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Aull
 */
public class DetailProduct extends javax.swing.JFrame {

    /**
     * Creates new form DetailProduct
     */
    public DetailProduct() {
        initComponents();
        ImageIcon LoginImage = new ImageIcon(getClass().getClassLoader().getResource("resources/jersey.png"));
        jGambar.setIcon(LoginImage);
        jCmbSize.getEditor().getEditorComponent().setBackground(Color.decode("#EC7FA9"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jLabelHarga = new javax.swing.JLabel();
        jCmbSize = new javax.swing.JComboBox<>();
        jTxtJumlah = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelDes = new javax.swing.JLabel();
        jBtnCancel = new javax.swing.JButton();
        jBtnCheckout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jGambar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 237, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 120));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 127, 169));
        jLabel1.setText("B  A  Z  F  F");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 310, 70));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelNama.setFont(new java.awt.Font("Arial", 0, 38)); // NOI18N
        jLabelNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNama.setText("Jersey Short Jacket");
        jPanel2.add(jLabelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 240, 360, -1));

        jLabelHarga.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabelHarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHarga.setText("Rp.500.000-,");
        jPanel2.add(jLabelHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 280, -1, -1));

        jCmbSize.setBackground(new java.awt.Color(236, 127, 169));
        jCmbSize.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jCmbSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XXL", "XL", "L", "M", "S", "XS" }));
        jCmbSize.setPreferredSize(new java.awt.Dimension(250, 60));
        jCmbSize.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jCmbSizeFocusGained(evt);
            }
        });
        jPanel2.add(jCmbSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 410, -1, -1));

        jTxtJumlah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(236, 127, 169), new java.awt.Color(236, 127, 169), new java.awt.Color(236, 127, 169), new java.awt.Color(236, 127, 169)));
        jTxtJumlah.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel2.add(jTxtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 510, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 127, 169));
        jLabel5.setText("Masukan Jumlah");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 490, 140, -1));

        jLabelDes.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabelDes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDes.setText("<html><div style='text-align: center;'>Jersey Short Jacket elegan dengan bahan lembut, bikin tampil menarik dan tetap hangat</div></html>");
        jPanel2.add(jLabelDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 340, 360, 30));

        jBtnCancel.setBackground(new java.awt.Color(255, 237, 250));
        jBtnCancel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBtnCancel.setForeground(new java.awt.Color(236, 127, 169));
        jBtnCancel.setText("Cancel");
        jBtnCancel.setPreferredSize(new java.awt.Dimension(200, 60));
        jBtnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCancelMouseClicked(evt);
            }
        });
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 610, -1, -1));

        jBtnCheckout.setBackground(new java.awt.Color(236, 127, 169));
        jBtnCheckout.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBtnCheckout.setForeground(new java.awt.Color(255, 237, 250));
        jBtnCheckout.setText("Checkout");
        jBtnCheckout.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel2.add(jBtnCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 610, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(550, 550));

        jGambar.setPreferredSize(new java.awt.Dimension(550, 550));
        jPanel3.add(jGambar);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 550, 560));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCmbSizeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCmbSizeFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCmbSizeFocusGained

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelActionPerformed

    private void jBtnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCancelMouseClicked
        this.dispose();
    }//GEN-LAST:event_jBtnCancelMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnCheckout;
    private javax.swing.JComboBox<String> jCmbSize;
    private javax.swing.JLabel jGambar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDes;
    private javax.swing.JLabel jLabelHarga;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTxtJumlah;
    // End of variables declaration//GEN-END:variables
}
