/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bazff.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author fauza
 */
public class HomePage extends javax.swing.JFrame {

    /** Creates new form HomePage */
    public HomePage() {
    initComponents();

    // Dummy data produk
    String[] namaProduk = {
        "Work Shirt", "Jersey", "Jorts Pants", "Adidas Pants",
        "Striped T-Shirt", "Black Sweater", "Pocket Shirt", "Denim Jorts Pants"
    };

    String[] gambarProduk = {
        "Work_Shirt.png", "jersey.png", "Jorts_Pants1.png", "Adidas_TShirt.png",
        "Stripped_TShirt.png", "Black_Sweater.png", "Pocket_Shirt.png", "Jorts_Pants2.png"
    };

    for (int i = 0; i < namaProduk.length; i++) {
        JPanel panelProduk = new JPanel();
        panelProduk.setPreferredSize(new Dimension(250, 300));
        panelProduk.setLayout(new BorderLayout());
        panelProduk.setBackground(Color.WHITE);

        // Gambar
        JLabel labelGambar = new JLabel();
        labelGambar.setHorizontalAlignment(JLabel.CENTER);

        ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("resources/" + gambarProduk[i]));
        Image img = icon.getImage().getScaledInstance(320, 320, Image.SCALE_SMOOTH);
        labelGambar.setIcon(new ImageIcon(img));

        // Nama Produk
        JLabel labelNama = new JLabel(namaProduk[i], JLabel.CENTER);
        labelNama.setFont(new Font("Arial", Font.BOLD, 16));
        labelNama.setBorder(BorderFactory.createEmptyBorder(10, 0, 10, 0));

        // Tombol
        JButton tombolDetail = new JButton("Lihat Detail");
        tombolDetail.setFocusable(false);
        tombolDetail.addActionListener((ActionEvent e) -> {
            JOptionPane.showMessageDialog(null, "Produk: " + labelNama.getText());
        });

        // Tambahkan komponen ke panel
        panelProduk.add(labelGambar, BorderLayout.CENTER);
        panelProduk.add(labelNama, BorderLayout.NORTH);
        panelProduk.add(tombolDetail, BorderLayout.SOUTH);

        jPanelProdukGrid.add(panelProduk);
    }

    // Refresh tampilan
    jPanelProdukGrid.revalidate();
    jPanelProdukGrid.repaint();
}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelProdukGrid = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Page");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 237, 250));
        jPanel2.setPreferredSize(new java.awt.Dimension(1920, 135));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 127, 169));
        jLabel1.setText("B A Z F F");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 35, -1, -1));

        jPanel3.setBackground(new java.awt.Color(236, 127, 169));
        jPanel3.setPreferredSize(new java.awt.Dimension(70, 70));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 237, 250));
        jLabel3.setText("X");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 13, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1820, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelProdukGrid.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProdukGrid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelProdukGrid.setPreferredSize(new java.awt.Dimension(250, 300));
        jPanelProdukGrid.setLayout(new java.awt.GridLayout(2, 0, 10, 10));
        jPanel1.add(jPanelProdukGrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 1770, 830));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelProdukGrid;
    // End of variables declaration//GEN-END:variables

}
