/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bazff.view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import bazff.config.Database;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 *
 * @author Aull
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        ImageIcon LoginImage = new ImageIcon(getClass().getClassLoader().getResource("resources/login.jpg"));
        jLogin.setIcon(LoginImage);
    }

    public JTextField getjTxtEmail() {
        return jTxtEmail;
    }

    public JTextField getjTxtPass() {
        return jTxtPass;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabellJudul = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtPass = new javax.swing.JTextField();
        jTxtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBtnSign = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabellJudul.setFont(new java.awt.Font("Tahoma", 0, 55)); // NOI18N
        jLabellJudul.setForeground(new java.awt.Color(236, 127, 169));
        jLabellJudul.setText("B  A  Z  F  F");
        jPanel1.add(jLabellJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, -1, 81));

        jPanel3.setPreferredSize(new java.awt.Dimension(800, 850));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 560, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 127, 169));
        jLabel2.setText("Modern Style");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 127, 169));
        jLabel3.setText("<html>HOLLA, WELCOME!</html>");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, 400, -1));

        jTxtPass.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTxtPass.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 1, new java.awt.Color(236, 127, 169)));
        jTxtPass.setPreferredSize(new java.awt.Dimension(600, 80));
        jPanel1.add(jTxtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 600, -1, -1));

        jTxtEmail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTxtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 1, new java.awt.Color(236, 127, 169)));
        jTxtEmail.setPreferredSize(new java.awt.Dimension(600, 80));
        jPanel1.add(jTxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 460, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 127, 169));
        jLabel5.setText("Username");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 430, 150, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 127, 169));
        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 570, 120, -1));

        jBtnSign.setBackground(new java.awt.Color(236, 127, 169));
        jBtnSign.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBtnSign.setForeground(new java.awt.Color(255, 237, 250));
        jBtnSign.setText("Log in");
        jBtnSign.setBorder(null);
        jBtnSign.setPreferredSize(new java.awt.Dimension(200, 60));
        jBtnSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnSignMouseClicked(evt);
            }
        });
        jBtnSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSignActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 720, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSignMouseClicked
        String username = jTxtEmail.getText().trim();
    String password = jTxtPass.getText().trim();

    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username dan Password tidak boleh kosong!");
        return;
    }

    try {
        Connection conn = Database.getKoneksi();
        String sql = "SELECT * FROM user WHERE username = ? AND password = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, username);
        pst.setString(2, password);

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            String nama = rs.getString("nama_pegawai");
            String role = rs.getString("role");

            // Buka form berdasarkan role
            if (role.equalsIgnoreCase("admin")) {
                new MainWindow().setVisible(true); // Ganti sesuai form admin
            } else {
                new HomePage().setVisible(true); // Ganti sesuai form pegawai
            }
            this.dispose(); // Tutup form login
        }

        rs.close();
        pst.close();
        conn.close();

    } catch (HeadlessException | SQLException e) {
        JOptionPane.showMessageDialog(this, "Pasword atau Username salah" );
    }
    }//GEN-LAST:event_jBtnSignMouseClicked

    private void jBtnSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSignActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSign;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabellJudul;
    private javax.swing.JLabel jLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtPass;
    // End of variables declaration//GEN-END:variables
}
