/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bazff.view;

import bazff.config.Database;
import bazff.controller.CartController;
import bazff.controller.HomePageController;
import bazff.controller.TransactionController;
import bazff.dao.SizeDAO;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Map;
import javax.swing.Box;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author bisma
 */
public class ShoppingCartView extends javax.swing.JFrame {

    private TransactionController transactionController;
    private CartController cartController;
    private HomePageController homePageController;
    private MainWindow mainWindow;
    private HomePage homePage;
    private JPanel[] produkPanels;  

    public ShoppingCartView(HomePageController homePageController, MainWindow window) {
        initComponents();
        this.mainWindow = window;
        this.homePageController = homePageController;
        this.cartController = new CartController();
        this.homePage = new HomePage();
        this.transactionController = new TransactionController(window);
        
        try {
            Connection conn = Database.getKoneksi();
            SizeDAO sizeDAO = new SizeDAO(conn);
            Map<Integer, String> sizeMap = sizeDAO.getSizeMap();

            // Lalu panggil method generate dengan sizeMap
            produkPanels = CartController.generateDaftarPanels(cartController, sizeMap);

        } catch (SQLException e) {
            e.printStackTrace();
        }
        for (JPanel p : produkPanels) {
            jPanelListDaftar.add(p);
            jPanelListDaftar.add(Box.createVerticalStrut(10));
        }
        jPanelListDaftar.revalidate();
        jPanelListDaftar.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelListDaftar = new javax.swing.JPanel();
        jBtnProceed = new javax.swing.JButton();
        jTextFieldTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 230, 248));
        jPanel2.setPreferredSize(new java.awt.Dimension(1920, 127));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(236, 127, 169));
        jPanel3.setPreferredSize(new java.awt.Dimension(65, 65));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1830, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 127, 169));
        jLabel2.setText("SHOPPING CART");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 127, 169));
        jLabel3.setText("B A Z F F");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelListDaftar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelListDaftar.setPreferredSize(new java.awt.Dimension(1920, 220));
        jPanelListDaftar.setLayout(new javax.swing.BoxLayout(jPanelListDaftar, javax.swing.BoxLayout.Y_AXIS));
        jPanel1.add(jPanelListDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, 740));

        jBtnProceed.setBackground(new java.awt.Color(236, 127, 169));
        jBtnProceed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnProceed.setForeground(new java.awt.Color(255, 237, 250));
        jBtnProceed.setText("Proceed to Checkout");
        jBtnProceed.setBorder(null);
        jBtnProceed.setPreferredSize(new java.awt.Dimension(250, 60));
        jBtnProceed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnProceedMouseClicked(evt);
            }
        });
        jBtnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProceedActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnProceed, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 930, -1, -1));

        jTextFieldTotal.setBackground(new java.awt.Color(255, 230, 248));
        jTextFieldTotal.setFont(new java.awt.Font("Dialog", 0, 35)); // NOI18N
        jTextFieldTotal.setText("Total    =     Rp 300.000-,");
        jTextFieldTotal.setPreferredSize(new java.awt.Dimension(400, 60));
        jPanel1.add(jTextFieldTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 930, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        cartController.setHomePage(homePage);
        cartController.KeluarPage(this);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jBtnProceedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnProceedMouseClicked
        transactionController.paymentPopUp();
    }//GEN-LAST:event_jBtnProceedMouseClicked

    private void jBtnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProceedActionPerformed
        // TODO add your handling code here:
        System.out.println(cartController.getDaftarProduct());
    }//GEN-LAST:event_jBtnProceedActionPerformed

    public JPanel getjPanel3() {
        return jPanel3;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnProceed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelListDaftar;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
}
