/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bazff.view;

/**
 *
 * @author USER
 */
public class SizeData extends javax.swing.JFrame {

    /**
     * Creates new form SizeData
     */
    public SizeData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDasar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanelHome = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PanelProduct = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        PanelSize = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PanelAddProduct = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        PanelTransaction1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelDasar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDasar.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanelDasar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 230, 248));
        jPanel1.setPreferredSize(new java.awt.Dimension(314, 936));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 55)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 127, 169));
        jLabel3.setText("B A Z F F");

        PanelHome.setBackground(new java.awt.Color(255, 230, 248));
        PanelHome.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(236, 127, 169)));
        PanelHome.setPreferredSize(new java.awt.Dimension(314, 68));
        PanelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelHomeMouseExited(evt);
            }
        });
        PanelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 127, 169));
        jLabel4.setText("Home");
        PanelHome.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 15, -1, -1));

        PanelProduct.setBackground(new java.awt.Color(255, 230, 248));
        PanelProduct.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(236, 127, 169)));
        PanelProduct.setPreferredSize(new java.awt.Dimension(314, 68));
        PanelProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelProductMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelProductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelProductMouseExited(evt);
            }
        });
        PanelProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 127, 169));
        jLabel5.setText("Product Data");
        PanelProduct.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 15, -1, -1));

        PanelSize.setBackground(new java.awt.Color(255, 230, 248));
        PanelSize.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(236, 127, 169)));
        PanelSize.setPreferredSize(new java.awt.Dimension(314, 68));
        PanelSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelSizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelSizeMouseExited(evt);
            }
        });
        PanelSize.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 127, 169));
        jLabel6.setText("Size Data");
        PanelSize.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 15, -1, -1));

        PanelAddProduct.setBackground(new java.awt.Color(255, 230, 248));
        PanelAddProduct.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(236, 127, 169)));
        PanelAddProduct.setPreferredSize(new java.awt.Dimension(314, 68));
        PanelAddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelAddProductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelAddProductMouseExited(evt);
            }
        });
        PanelAddProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 127, 169));
        jLabel7.setText("Add Product");
        PanelAddProduct.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 15, -1, -1));

        PanelTransaction1.setBackground(new java.awt.Color(255, 230, 248));
        PanelTransaction1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(236, 127, 169)));
        PanelTransaction1.setPreferredSize(new java.awt.Dimension(314, 68));
        PanelTransaction1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelTransaction1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelTransaction1MouseExited(evt);
            }
        });
        PanelTransaction1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 127, 169));
        jLabel8.setText("Transaction Data");
        PanelTransaction1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 15, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3))
                    .addComponent(PanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelTransaction1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3)
                .addGap(153, 153, 153)
                .addComponent(PanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(PanelProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(PanelSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(PanelTransaction1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(PanelAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jPanelDasar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 72, -1, 860));

        getContentPane().add(jPanelDasar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelHomeMouseClicked
        windowController.tampilHalamanUtama(this);
    }//GEN-LAST:event_PanelHomeMouseClicked

    private void PanelHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelHomeMouseEntered
        PanelHome.setBackground(new Color(236, 127, 169));
        jLabel4.setForeground(new Color(255, 230, 248));
    }//GEN-LAST:event_PanelHomeMouseEntered

    private void PanelHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelHomeMouseExited
        PanelHome.setBackground(new Color(255, 230, 248));
        jLabel4.setForeground(new Color(236, 127, 169));
    }//GEN-LAST:event_PanelHomeMouseExited

    private void PanelProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelProductMouseClicked
        windowController.tampilHalamanProduct(this);
    }//GEN-LAST:event_PanelProductMouseClicked

    private void PanelProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelProductMouseEntered
        PanelProduct.setBackground(new Color(236, 127, 169));
        jLabel2.setForeground(new Color(255, 230, 248));
    }//GEN-LAST:event_PanelProductMouseEntered

    private void PanelProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelProductMouseExited
        PanelProduct.setBackground(new Color(255, 230, 248));
        jLabel2.setForeground(new Color(236, 127, 169));
    }//GEN-LAST:event_PanelProductMouseExited

    private void PanelSizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSizeMouseEntered
        PanelSize.setBackground(new Color(236, 127, 169));
        jLabel5.setForeground(new Color(255, 230, 248));
    }//GEN-LAST:event_PanelSizeMouseEntered

    private void PanelSizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSizeMouseExited
        PanelSize.setBackground(new Color(255, 230, 248));
        jLabel5.setForeground(new Color(236, 127, 169));
    }//GEN-LAST:event_PanelSizeMouseExited

    private void PanelAddProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAddProductMouseEntered
        PanelAddProduct.setBackground(new Color(236, 127, 169));
        jLabel3.setForeground(new Color(255, 230, 248));
    }//GEN-LAST:event_PanelAddProductMouseEntered

    private void PanelAddProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAddProductMouseExited
        PanelAddProduct.setBackground(new Color(255, 230, 248));
        jLabel3.setForeground(new Color(236, 127, 169));
    }//GEN-LAST:event_PanelAddProductMouseExited

    private void PanelTransaction1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelTransaction1MouseEntered
        PanelTransaction1.setBackground(new Color(236, 127, 169));
        jLabel6.setForeground(new Color(255, 230, 248));
    }//GEN-LAST:event_PanelTransaction1MouseEntered

    private void PanelTransaction1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelTransaction1MouseExited
        PanelTransaction1.setBackground(new Color(255, 230, 248));
        jLabel6.setForeground(new Color(236, 127, 169));
    }//GEN-LAST:event_PanelTransaction1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SizeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SizeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SizeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SizeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SizeData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAddProduct;
    private javax.swing.JPanel PanelHome;
    private javax.swing.JPanel PanelProduct;
    private javax.swing.JPanel PanelSize;
    private javax.swing.JPanel PanelTransaction1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDasar;
    // End of variables declaration//GEN-END:variables
}
