/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bazff.view;

/**
 *
 * @author USER
 */
public class SizeData extends javax.swing.JFrame {

    /**
     * Creates new form SizeData
     */
    public SizeData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDasar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        SizePanel = new javax.swing.JPanel();
        PanelHeader = new javax.swing.JPanel();
        SizePanelHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelDasar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDasar.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanelDasar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 230, 248));
        jPanel1.setPreferredSize(new java.awt.Dimension(314, 936));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 55)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 127, 169));
        jLabel3.setText("B A Z F F");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3)
                .addContainerGap(733, Short.MAX_VALUE))
        );

        jPanelDasar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 72, -1, 860));

        SizePanel.setBackground(new java.awt.Color(255, 230, 248));
        SizePanel.setPreferredSize(new java.awt.Dimension(1440, 730));

        javax.swing.GroupLayout SizePanelLayout = new javax.swing.GroupLayout(SizePanel);
        SizePanel.setLayout(SizePanelLayout);
        SizePanelLayout.setHorizontalGroup(
            SizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        SizePanelLayout.setVerticalGroup(
            SizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        jPanelDasar.add(SizePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 202, -1, -1));

        PanelHeader.setBackground(new java.awt.Color(255, 184, 224));
        PanelHeader.setLayout(new java.awt.CardLayout());

        SizePanelHeader.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        SizePanelHeader.setForeground(new java.awt.Color(236, 127, 169));
        SizePanelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SizePanelHeader.setText("SIZE DATA");
        SizePanelHeader.setPreferredSize(new java.awt.Dimension(1440, 127));
        PanelHeader.add(SizePanelHeader, "card2");

        jPanelDasar.add(PanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 72, -1, -1));

        getContentPane().add(jPanelDasar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SizeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SizeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SizeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SizeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SizeData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHeader;
    private javax.swing.JPanel SizePanel;
    private javax.swing.JLabel SizePanelHeader;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDasar;
    // End of variables declaration//GEN-END:variables
}
