/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bazff.view;


import bazff.controller.SizeController;
import bazff.controller.TableController;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author bisma
 */
public class SizeDataView extends javax.swing.JPanel {

    /**
     * Creates new form ProductDataPanel
     */
    private MainWindow mainWindow;
    private SizeController sizeController;
    private TableController tableController;
    
    public SizeDataView(MainWindow mainWindow) {
        this.mainWindow = mainWindow;
        initComponents();
        sizeController = new SizeController(mainWindow);
        this.tableController = new TableController(this);
        tableController.setUpTableSize();
    }

    public JTable getTableSize() {
        return TableSize;
    }
    
    SizeDataView() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelHeaderSizeData = new javax.swing.JPanel();
        PanelHeaderSize = new javax.swing.JLabel();
        PanelSizeData = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSize = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1440, 858));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelHeaderSizeData.setBackground(new java.awt.Color(255, 184, 224));
        PanelHeaderSizeData.setPreferredSize(new java.awt.Dimension(1440, 127));
        PanelHeaderSizeData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelHeaderSize.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        PanelHeaderSize.setForeground(new java.awt.Color(236, 127, 169));
        PanelHeaderSize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelHeaderSize.setText("SIZE DATA");
        PanelHeaderSize.setPreferredSize(new java.awt.Dimension(1440, 127));
        PanelHeaderSizeData.add(PanelHeaderSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(PanelHeaderSizeData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelSizeData.setBackground(new java.awt.Color(255, 230, 248));
        PanelSizeData.setPreferredSize(new java.awt.Dimension(1440, 730));
        PanelSizeData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAdd.setBackground(new java.awt.Color(236, 127, 169));
        jButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 230, 248));
        jButtonAdd.setText("Add");
        jButtonAdd.setBorder(null);
        jButtonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddMouseClicked(evt);
            }
        });
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        PanelSizeData.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 610, 236, 72));

        jPanel2.setBackground(new java.awt.Color(255, 230, 248));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 184, 224)));
        jPanel2.setForeground(new java.awt.Color(236, 127, 169));
        jPanel2.setPreferredSize(new java.awt.Dimension(410, 44));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 127, 169));
        jLabel1.setText("SIZE");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 7, -1, -1));

        PanelSizeData.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 59, -1, 50));

        TableSize.setBackground(new java.awt.Color(255, 255, 255));
        TableSize.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        TableSize.setForeground(new java.awt.Color(0, 0, 0));
        TableSize.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"XL"},
                {"M"},
                {"L"},
                {"S"},
                {"XS"},
                {"XXL"}
            },
            new String [] {
                "Size Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableSize);

        PanelSizeData.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 410, 380));

        jButton1.setBackground(new java.awt.Color(255, 184, 224));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 230, 248));
        jButton1.setText("Delete");
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(236, 72));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        PanelSizeData.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 610, -1, -1));

        add(PanelSizeData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddMouseClicked
        sizeController.addSizeDataPopUp();
    }//GEN-LAST:event_jButtonAddMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        sizeController.deleteSizeDataPopUp();
    }//GEN-LAST:event_jButton1MouseClicked

    public JPanel getPanelHeaderSizeData() {
        return PanelHeaderSizeData;
    }

    public JPanel getPanelSizeData() {
        return PanelSizeData;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PanelHeaderSize;
    private javax.swing.JPanel PanelHeaderSizeData;
    private javax.swing.JPanel PanelSizeData;
    private javax.swing.JTable TableSize;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
